# Author: Hananto Wicaksono
# SPDX-License-Identifier: GPL-3.0-or-later

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mysql-router

resources:
  - namespace.yaml
  - mysqlrouter-crd.yaml
  - secret.yaml
  - operator-rbac.yaml
  - operator-deployment.yaml
  - mysqlrouter.yaml
