apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mysql-router

resources:
  - namespace.yaml
  - mysqlrouter-crd.yaml
  - secret.yaml
  - operator-rbac.yaml
  - operator-deployment.yaml
  - mysqlrouter.yaml

configMapGenerator:
  - name: mysql-router-operator-code
    files:
      - operator.py
      - requirements.txt

generatorOptions:
  disableNameSuffixHash: true
