apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-router-operator
  namespace: mysql-router
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-router-operator
  namespace: mysql-router
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "configmaps", "secrets", "events"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["services/finalizers", "endpoints/finalizers", "configmaps/finalizers"]
    verbs: ["patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments/finalizers"]
    verbs: ["patch", "update"]
  - apiGroups: ["mysql.oracle.com"]
    resources: ["mysqlrouters"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["mysql.oracle.com"]
    resources: ["mysqlrouters/status", "mysqlrouters/finalizers"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-router-operator
  namespace: mysql-router
subjects:
  - kind: ServiceAccount
    name: mysql-router-operator
    namespace: mysql-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mysql-router-operator
