# Author: Hananto Wicaksono
# SPDX-License-Identifier: GPL-3.0-or-later

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-router-operator
  namespace: mysql-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-router-operator
  template:
    metadata:
      labels:
        app: mysql-router-operator
    spec:
      serviceAccountName: mysql-router-operator
      containers:
        - name: operator
          image: ghcr.io/tripplea-sg/mysql-router-operator:0.1.5
          imagePullPolicy: Always
          env:
            - name: ROUTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ROUTER_NAME
              value: mysql-router
            - name: BOOTSTRAP_SECRET
              value: mysql-router-bootstrap
            - name: CLUSTER_LABEL
              value: mysql.oracle.com/innodb-cluster
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
