apiVersion: v1
kind: Secret
metadata:
  name: mysql-router-bootstrap
  namespace: mysql-router
type: Opaque
stringData:
  MYSQL_BOOTSTRAP_USER: gradmin
  MYSQL_BOOTSTRAP_PASSWORD: grpass
  MYSQL_BOOTSTRAP_HOST: placeholder
  MYSQL_BOOTSTRAP_PORT: '3306'
